/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/stone/stoneTheme.ts
 * Command: astryx theme build src/themes/stone/stoneTheme.ts
 * Generated: 2026-07-19T21:01:21.976Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const stoneIconRegistry: IconRegistry;
export declare const stoneTheme: DefinedTheme;
