/**
 * This file is auto-generated. Do not edit this file manually.
 * To regenerate the schema, from your project root:
 *
 *   cd convex/betterAuth
 *   npx auth generate
 *
 * To customize the schema, generate to an alternate file and import
 * the table definitions to your schema file. See
 * https://labs.convex.dev/better-auth/features/local-install#adding-custom-indexes.
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const tables = {
  account: defineTable({
    accessToken: v.optional(v.union(v.null(), v.string())),
    accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    accountId: v.string(),
    createdAt: v.number(),
    idToken: v.optional(v.union(v.null(), v.string())),
    password: v.optional(v.union(v.null(), v.string())),
    providerId: v.string(),
    refreshToken: v.optional(v.union(v.null(), v.string())),
    refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    scope: v.optional(v.union(v.null(), v.string())),
    updatedAt: v.number(),
    userId: v.string(),
  })
    .index("accountId", ["accountId"])
    .index("accountId_providerId", ["accountId", "providerId"])
    .index("providerId_userId", ["providerId", "userId"])
    .index("userId", ["userId"]),
  invite: defineTable({
    createdAt: v.optional(v.union(v.null(), v.number())),
    createdByUserId: v.optional(v.union(v.null(), v.string())),
    email: v.optional(v.union(v.null(), v.string())),
    emails: v.optional(v.union(v.null(), v.array(v.string()))),
    expiresAt: v.number(),
    // Hand-added (not part of better-invite's own schema — see
    // node_modules/better-invite/dist/schema.mjs): group ids to assign to the
    // new user at signup (see convex/auth.ts's applyInviteGroups hook and
    // convex/invites/mutations.ts#createInvite). Re-running `npx auth generate`
    // will not know about this field — it must be re-added by hand afterward,
    // same as the `status` field's hand-fix below.
    groupIds: v.optional(v.array(v.string())),
    infinityMaxUses: v.boolean(),
    maxUses: v.number(),
    newAccount: v.optional(v.union(v.null(), v.boolean())),
    redirectToAfterUpgrade: v.optional(v.union(v.null(), v.string())),
    role: v.string(),
    shareInviterName: v.boolean(),
    // `@better-auth/cli generate` can't infer a Convex validator for
    // better-invite's `status: { type: [...] }` enum field shape (see
    // node_modules/better-invite/dist/schema.mjs) and emits `undefined`
    // here on every regeneration — hand-fixed to match that source of truth.
    status: v.union(
      v.literal("pending"),
      v.literal("rejected"),
      v.literal("canceled"),
      v.literal("used")
    ),
    token: v.optional(v.union(v.null(), v.string())),
  })
    .index("token", ["token"])
    .index("createdByUserId", ["createdByUserId"]),
  inviteUse: defineTable({
    inviteId: v.string(),
    usedAt: v.number(),
    usedByUserId: v.optional(v.union(v.null(), v.string())),
  })
    .index("inviteId", ["inviteId"])
    .index("usedByUserId", ["usedByUserId"]),
  jwks: defineTable({
    createdAt: v.number(),
    expiresAt: v.optional(v.union(v.null(), v.number())),
    privateKey: v.string(),
    publicKey: v.string(),
  }),
  session: defineTable({
    createdAt: v.number(),
    expiresAt: v.number(),
    impersonatedBy: v.optional(v.union(v.null(), v.string())),
    ipAddress: v.optional(v.union(v.null(), v.string())),
    token: v.string(),
    updatedAt: v.number(),
    userAgent: v.optional(v.union(v.null(), v.string())),
    userId: v.string(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("expiresAt_userId", ["expiresAt", "userId"])
    .index("token", ["token"])
    .index("userId", ["userId"]),
  user: defineTable({
    banExpires: v.optional(v.union(v.null(), v.number())),
    banReason: v.optional(v.union(v.null(), v.string())),
    banned: v.optional(v.union(v.null(), v.boolean())),
    createdAt: v.number(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.optional(v.union(v.null(), v.string())),
    name: v.string(),
    role: v.optional(v.union(v.null(), v.string())),
    updatedAt: v.number(),
    userId: v.optional(v.union(v.null(), v.string())),
  })
    .index("email_name", ["email", "name"])
    .index("name", ["name"])
    .index("userId", ["userId"]),
  verification: defineTable({
    createdAt: v.number(),
    expiresAt: v.number(),
    identifier: v.string(),
    updatedAt: v.number(),
    value: v.string(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("identifier", ["identifier"]),
};

const schema = defineSchema(tables);

export default schema;
