/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin/users'
import { Route as AuthedAdminInvitesRouteImport } from './routes/_authed/admin/invites'
import { Route as AuthedAdminGroupsRouteImport } from './routes/_authed/admin/groups'
import { Route as AuthedAdminFilesRouteImport } from './routes/_authed/admin/files'
import { Route as AuthedAdminClustersRouteImport } from './routes/_authed/admin/clusters'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminInvitesRoute = AuthedAdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminGroupsRoute = AuthedAdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminFilesRoute = AuthedAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminClustersRoute = AuthedAdminClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/admin/clusters': typeof AuthedAdminClustersRoute
  '/admin/files': typeof AuthedAdminFilesRoute
  '/admin/groups': typeof AuthedAdminGroupsRoute
  '/admin/invites': typeof AuthedAdminInvitesRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthedIndexRoute
  '/admin/clusters': typeof AuthedAdminClustersRoute
  '/admin/files': typeof AuthedAdminFilesRoute
  '/admin/groups': typeof AuthedAdminGroupsRoute
  '/admin/invites': typeof AuthedAdminInvitesRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/admin': typeof AuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/clusters': typeof AuthedAdminClustersRoute
  '/_authed/admin/files': typeof AuthedAdminFilesRoute
  '/_authed/admin/groups': typeof AuthedAdminGroupsRoute
  '/_authed/admin/invites': typeof AuthedAdminInvitesRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/invite/$token'
    | '/admin/clusters'
    | '/admin/files'
    | '/admin/groups'
    | '/admin/invites'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/invite/$token'
    | '/'
    | '/admin/clusters'
    | '/admin/files'
    | '/admin/groups'
    | '/admin/invites'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/admin'
    | '/invite/$token'
    | '/_authed/'
    | '/_authed/admin/clusters'
    | '/_authed/admin/files'
    | '/_authed/admin/groups'
    | '/_authed/admin/invites'
    | '/_authed/admin/users'
    | '/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/invites': {
      id: '/_authed/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthedAdminInvitesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/groups': {
      id: '/_authed/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthedAdminGroupsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/files': {
      id: '/_authed/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthedAdminFilesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/clusters': {
      id: '/_authed/admin/clusters'
      path: '/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AuthedAdminClustersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminClustersRoute: typeof AuthedAdminClustersRoute
  AuthedAdminFilesRoute: typeof AuthedAdminFilesRoute
  AuthedAdminGroupsRoute: typeof AuthedAdminGroupsRoute
  AuthedAdminInvitesRoute: typeof AuthedAdminInvitesRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminClustersRoute: AuthedAdminClustersRoute,
  AuthedAdminFilesRoute: AuthedAdminFilesRoute,
  AuthedAdminGroupsRoute: AuthedAdminGroupsRoute,
  AuthedAdminInvitesRoute: AuthedAdminInvitesRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
