import { defineTheme } from "@astryxdesign/core/theme";

export const themeTheme = defineTheme({
  components: {
    badge: {
      "variant:blue": {
        backgroundColor: "var(--color-background-blue)",
        color: "var(--color-text-blue)",
      },
      "variant:cyan": {
        backgroundColor: "var(--color-background-cyan)",
        color: "var(--color-text-cyan)",
      },
      "variant:error": {
        backgroundColor: "light-dark(#e33f4a, #ff705d)",
        color: "light-dark(#ffffff, #171717)",
      },
      "variant:gray": {
        backgroundColor: "var(--color-background-gray)",
        color: "var(--color-text-gray)",
      },
      "variant:green": {
        backgroundColor: "var(--color-background-green)",
        color: "var(--color-text-green)",
      },
      "variant:info": {
        backgroundColor: "light-dark(#0074e2, #6d9cfe)",
        color: "light-dark(#ffffff, #171717)",
      },
      "variant:neutral": {
        backgroundColor: "var(--color-background-gray)",
        color: "var(--color-text-gray)",
      },
      "variant:orange": {
        backgroundColor: "var(--color-background-orange)",
        color: "var(--color-text-orange)",
      },
      "variant:pink": {
        backgroundColor: "var(--color-background-pink)",
        color: "var(--color-text-pink)",
      },
      "variant:purple": {
        backgroundColor: "var(--color-background-purple)",
        color: "var(--color-text-purple)",
      },
      "variant:red": {
        backgroundColor: "var(--color-background-red)",
        color: "var(--color-text-red)",
      },
      "variant:success": {
        backgroundColor: "light-dark(#198100, #64af4c)",
        color: "light-dark(#ffffff, #171717)",
      },
      "variant:teal": {
        backgroundColor: "var(--color-background-teal)",
        color: "var(--color-text-teal)",
      },
      "variant:warning": {
        backgroundColor: "#ffce2f",
        color: "#171717",
      },
      "variant:yellow": {
        backgroundColor: "var(--color-background-yellow)",
        color: "var(--color-text-yellow)",
      },
    },
    banner: {
      "status:error": {
        "--color-error": "var(--color-text-red)",
        "--color-text-primary": "var(--color-text-red)",
        "--color-text-secondary": "var(--color-text-red)",
      },
      "status:info": {
        "--color-accent": "var(--color-text-blue)",
        "--color-accent-muted": "transparent",
        "--color-text-primary": "var(--color-text-blue)",
        "--color-text-secondary": "var(--color-text-blue)",
        backgroundColor: "var(--color-background-blue)",
      },
      "status:success": {
        "--color-success": "var(--color-text-green)",
        "--color-text-primary": "var(--color-text-green)",
        "--color-text-secondary": "var(--color-text-green)",
      },
      "status:warning": {
        "--color-text-primary": "var(--color-text-yellow)",
        "--color-text-secondary": "var(--color-text-yellow)",
        "--color-warning": "var(--color-text-yellow)",
      },
    },
    button: {
      "variant:destructive": {
        backgroundColor: "var(--color-error-muted)",
        color: "var(--color-error)",
      },
    },
    card: {
      base: {
        padding: "var(--spacing-3)",
      },
    },
    heading: {
      "level:1": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-heading-1-size)",
        fontWeight: "var(--text-heading-1-weight)",
        lineHeight: "var(--text-heading-1-leading)",
      },
      "level:2": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-heading-2-size)",
        fontWeight: "var(--text-heading-2-weight)",
        lineHeight: "var(--text-heading-2-leading)",
      },
      "level:3": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-heading-3-size)",
        fontWeight: "var(--text-heading-3-weight)",
        lineHeight: "var(--text-heading-3-leading)",
      },
      "level:4": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-heading-4-size)",
        fontWeight: "var(--text-heading-4-weight)",
        lineHeight: "var(--text-heading-4-leading)",
      },
      "level:5": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-heading-5-size)",
        fontWeight: "var(--text-heading-5-weight)",
        lineHeight: "var(--text-heading-5-leading)",
      },
      "level:6": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-heading-6-size)",
        fontWeight: "var(--text-heading-6-weight)",
        lineHeight: "var(--text-heading-6-leading)",
      },
    },
    progressbar: {
      base: {
        "--color-background-muted": "var(--color-border-emphasized)",
      },
      "variant:accent": {
        "--color-accent": "#0074e2",
      },
      "variant:error": {
        "--color-error": "#e33f4a",
      },
      "variant:success": {
        "--color-success": "#198100",
      },
      "variant:warning": {
        "--color-warning": "#ffce2f",
      },
    },
    section: {
      base: {
        padding: "var(--spacing-3)",
      },
    },
    switch: {
      base: {
        "--color-background-gray": "var(--color-border-emphasized)",
      },
    },
    text: {
      "type:body": {
        fontFamily: "var(--font-family-body)",
        fontSize: "var(--text-body-size)",
        lineHeight: "var(--text-body-leading)",
      },
      "type:code": {
        fontFamily: "var(--font-family-code)",
        fontSize: "var(--text-code-size)",
        lineHeight: "var(--text-code-leading)",
      },
      "type:display-1": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-display-1-size)",
        lineHeight: "var(--text-display-1-leading)",
      },
      "type:display-2": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-display-2-size)",
        lineHeight: "var(--text-display-2-leading)",
      },
      "type:display-3": {
        fontFamily: "var(--font-family-heading)",
        fontSize: "var(--text-display-3-size)",
        lineHeight: "var(--text-display-3-leading)",
      },
      "type:label": {
        fontFamily: "var(--font-family-body)",
        fontSize: "var(--text-label-size)",
        lineHeight: "var(--text-label-leading)",
      },
      "type:large": {
        fontFamily: "var(--font-family-body)",
        fontSize: "var(--text-large-size)",
        lineHeight: "var(--text-large-leading)",
      },
      "type:supporting": {
        fontFamily: "var(--font-family-body)",
        fontSize: "var(--text-supporting-size)",
        lineHeight: "var(--text-supporting-leading)",
      },
    },
  },
  name: "theme",
  tokens: {
    "--color-accent": "light-dark(#262626, #4B72CE)",
    "--color-accent-muted":
      "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-background-blue": "light-dark(#c4ddfb, #9eb7ff3D)",
    "--color-background-body": "light-dark(#E9F3ED, #08130D)",
    "--color-background-card": "light-dark(#F4FFF8, #161D19)",
    "--color-background-cyan": "light-dark(#a3e0ef, #83c2d43D)",
    "--color-background-gray": "light-dark(#e5e5e5, var(--color-neutral))",
    "--color-background-green": "light-dark(#c5e5c0, #84c9803D)",
    "--color-background-inverted": "light-dark(#161D19, #F4FFF8)",
    "--color-background-muted": "light-dark(#161D190D, #161D1980)",
    "--color-background-orange": "light-dark(#fad0b5, #ffa2583D)",
    "--color-background-pink": "light-dark(#fccadc, #ff99c33D)",
    "--color-background-popover": "light-dark(#F4FFF8, #2A322D)",
    "--color-background-purple": "light-dark(#eccef3, #f297ff3D)",
    "--color-background-red": "light-dark(#facecb, #ff9e973D)",
    "--color-background-surface": "light-dark(#F4FFF8, #161D19)",
    "--color-background-teal": "light-dark(#a5e3d6, #7ec6b83D)",
    "--color-background-yellow": "light-dark(#f8da9d, #deb4333D)",
    "--color-border": "light-dark(#161D191A, #E9F3ED1A)",
    "--color-border-blue": "light-dark(#b1c9e7, #6d9cfe)",
    "--color-border-cyan": "light-dark(#91d3e3, #67a7b8)",
    "--color-border-emphasized": "light-dark(#9FAFA5, #3C4A42)",
    "--color-border-gray": "light-dark(#d4d4d4, #262626)",
    "--color-border-green": "light-dark(#b2d1ac, #69ad67)",
    "--color-border-orange": "light-dark(#e6bda2, #e2883e)",
    "--color-border-pink": "light-dark(#e7b7c8, #f273aa)",
    "--color-border-purple": "light-dark(#d8bbdf, #dd74f0)",
    "--color-border-red": "light-dark(#e6bab8, #ff6f6c)",
    "--color-border-teal": "light-dark(#94d6c8, #63ab9d)",
    "--color-border-yellow": "light-dark(#e4c279, #c0990e)",
    "--color-error": "light-dark(#a50c25, #ffc6c1)",
    "--color-error-muted": "light-dark(#facecb, #ff9e973D)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-blue": "light-dark(#00458c, #9eb7ff)",
    "--color-icon-cyan": "light-dark(#00505f, #83c2d4)",
    "--color-icon-disabled": "light-dark(#85948B, #536259)",
    "--color-icon-gray": "light-dark(#525252, #a3a3a3)",
    "--color-icon-green": "light-dark(#0c5700, #84c980)",
    "--color-icon-orange": "light-dark(#6e3500, #ffa258)",
    "--color-icon-pink": "light-dark(#83004b, #ff99c3)",
    "--color-icon-primary": "light-dark(#161D19, #DAE5DF)",
    "--color-icon-purple": "light-dark(#700084, #f297ff)",
    "--color-icon-red": "light-dark(#89001a, #ff9e97)",
    "--color-icon-secondary": "light-dark(#3C4A42, #9FAFA5)",
    "--color-icon-teal": "light-dark(#005348, #7ec6b8)",
    "--color-icon-yellow": "light-dark(#584400, #deb433)",
    "--color-neutral": "light-dark(#161D191A, #DAE5DF33)",
    "--color-on-accent": "light-dark(#FFFFFF, #003D14)",
    "--color-on-dark": "#ffffff",
    "--color-on-error": "light-dark(#ffffff, #171717)",
    "--color-on-light": "#171717",
    "--color-on-success": "light-dark(#ffffff, #171717)",
    "--color-on-warning": "#171717",
    "--color-overlay": "light-dark(#161D1966, #161D1999)",
    "--color-overlay-hover": "light-dark(#161D190D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#161D191A, #FFFFFF1A)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-skeleton": "light-dark(#9FAFA5, #3C4A42)",
    "--color-success": "light-dark(#007004, #9fe59b)",
    "--color-success-muted": "light-dark(#c5e5c0, #84c9803D)",
    "--color-syntax-attribute": "light-dark(#584400, #eec12f)",
    "--color-syntax-background": "light-dark(#fafafa, #0a0a0a)",
    "--color-syntax-comment": "light-dark(#737373, #a3a3a3)",
    "--color-syntax-constant": "light-dark(#6e3500, #ffb37f)",
    "--color-syntax-function": "light-dark(#00458c, #a0caff)",
    "--color-syntax-keyword": "light-dark(#700084, #efa8ff)",
    "--color-syntax-number": "light-dark(#6e3500, #ffb37f)",
    "--color-syntax-operator": "light-dark(#737373, #a3a3a3)",
    "--color-syntax-property": "light-dark(#005348, #83dac9)",
    "--color-syntax-punctuation": "light-dark(#a3a3a3, #525252)",
    "--color-syntax-string": "light-dark(#005600, #a6d2a2)",
    "--color-syntax-tag": "light-dark(#89001a, #ffaeaa)",
    "--color-syntax-type": "light-dark(#700084, #efa8ff)",
    "--color-syntax-variable": "light-dark(#171717, #e5e5e5)",
    "--color-text-accent": "var(--color-accent)",
    "--color-text-blue": "light-dark(#00458c, #c7d3ff)",
    "--color-text-cyan": "light-dark(#00505f, #9edef0)",
    "--color-text-disabled": "light-dark(#85948B, #536259)",
    "--color-text-gray": "light-dark(#262626, #e5e5e5)",
    "--color-text-green": "light-dark(#0c5700, #9fe59b)",
    "--color-text-orange": "light-dark(#6e3500, #ffc9a2)",
    "--color-text-pink": "light-dark(#83004b, #ffc3da)",
    "--color-text-primary": "light-dark(#161D19, #DAE5DF)",
    "--color-text-purple": "light-dark(#700084, #fac1ff)",
    "--color-text-red": "light-dark(#89001a, #ffc6c1)",
    "--color-text-secondary": "light-dark(#3C4A42, #9FAFA5)",
    "--color-text-teal": "light-dark(#005348, #99e2d3)",
    "--color-text-yellow": "light-dark(#584400, #fdcf4f)",
    "--color-track": "light-dark(#9FAFA5, #3C4A42)",
    "--color-warning": "light-dark(#745b00, #fdcf4f)",
    "--color-warning-muted": "light-dark(#f8da9d, #deb4333D)",
    "--font-family-body":
      'Figtree, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    "--font-family-code":
      'ui-monospace, "SF Mono", Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    "--font-family-heading": '"Inter", -apple-system, sans-serif',
    "--font-size-2xl": "1.9375rem",
    "--font-size-3xl": "2.4375rem",
    "--font-size-4xl": "3.0625rem",
    "--font-size-4xs": "0.3125rem",
    "--font-size-5xl": "3.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.25rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-xl": "1.5625rem",
    "--radius-chat": "84px",
    "--radius-container": "36px",
    "--radius-element": "24px",
    "--radius-inner": "12px",
    "--radius-page": "84px",
    "--shadow-high":
      "0 4px 6px light-dark(oklch(0 0 0 / 10%), oklch(0 0 0 / 50%)), 0 12px 24px light-dark(oklch(0 0 0 / 15%), oklch(0 0 0 / 70%)), inset 0 0 0 1px light-dark(transparent, oklch(1 0 0 / 15%))",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #e33f4a4D",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px rgba(38, 38, 38, 0.3)",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px rgba(38, 38, 38, 0.5)",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #1981004D",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #ffce2f4D",
    "--shadow-low":
      "0 2px 4px light-dark(oklch(0 0 0 / 5%), oklch(0 0 0 / 25%)), 0 4px 8px light-dark(oklch(0 0 0 / 10%), oklch(0 0 0 / 40%)), inset 0 0 0 1px light-dark(transparent, oklch(1 0 0 / 8%))",
    "--shadow-med":
      "0 2px 4px light-dark(oklch(0 0 0 / 5%), oklch(0 0 0 / 35%)), 0 4px 12px light-dark(oklch(0 0 0 / 10%), oklch(0 0 0 / 50%)), inset 0 0 0 1px light-dark(transparent, oklch(1 0 0 / 12%))",
    "--size-element-lg": "44px",
    "--size-element-md": "40px",
    "--size-element-sm": "36px",
    "--spacing-0-5": "3px",
    "--spacing-1": "6px",
    "--spacing-1-5": "9px",
    "--spacing-2": "12px",
    "--spacing-3": "18px",
    "--spacing-4": "24px",
    "--spacing-5": "30px",
    "--spacing-6": "36px",
    "--spacing-7": "42px",
    "--spacing-8": "48px",
    "--spacing-9": "54px",
    "--spacing-10": "60px",
    "--spacing-11": "66px",
    "--spacing-12": "72px",
    "--text-body-leading": "1.5",
    "--text-code-leading": "1.5",
    "--text-display-1-leading": "1.2459",
    "--text-display-2-leading": "1.2245",
    "--text-display-3-leading": "1.2308",
    "--text-heading-1-leading": "1.4194",
    "--text-heading-2-leading": "1.44",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-leading": "1.5385",
    "--text-label-leading": "1.5",
    "--text-large-leading": "1.4",
    "--text-supporting-leading": "1.5385",
  },
});
